---

- name: Setup project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_type: python
    project_path: .
    project_features:
      - test
      - docker
      - ci_cd
    project_python_submodules: []
    project_default_branch: main

    docker_image_name: wenet/survey-app
    docker_additional_commands:
      - RUN pip install uWSGI==2.0.19.1
    docker_python_services: 
      - name: survey
        main_module: manage.py
        django_uwsgi_config:
          app: wenet_survey
          settings: settings
          static_files_base_path: "/${BASE_URL}static/"
        required_env_variables:
          - ${WENET_APP_ID}
          - ${WENET_APP_SECRET}
          - ${WENET_INSTANCE_URL}
          - ${OAUTH_CALLBACK_URL}
          - ${SURVEY_FORM_ID_EN}
          - ${SURVEY_FORM_ID_IT}
          - ${SURVEY_FORM_ID_ES}
          - ${SURVEY_FORM_ID_MN}
          - ${SURVEY_FORM_ID_DA}
      - name: worker
        required_env_variables:
        custom_start_command: "exec celery -A wenet_survey worker -B -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"

    ci_release: true

    ci_environments:
      mr:
        stages:
          - name: test
            in_docker: false
          - name: test
            type: coverage
      staging:
        stages:
          - name: build
            manual: true
          - name: test
            in_docker: false
          - name: test
            type: coverage
          - name: push
          - name: trigger
            git_ref: develop
      production:
        stages:
          - name: build
          - name: test
            in_docker: false
          - name: test
            type: coverage
          - name: push
      issue:
        stages:
          - name: build
            type: badge
          - name: test
            type: coverage
      default:
        stages:
          - name: build
            type: badge
          - name: test
            type: coverage
    ci_additional_badges:
      - wenet-common

  roles:
    - uh.project_template