---

- name: Setup project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_type: python
    project_path: .
    project_features:
      - test
      - docker
      - ci_cd
      - deploy
    project_python_submodules: []
    project_default_branch: main

    docker_image_name: wenet/survey-app
    docker_python_services: 
      - name: survey
        main_module: manage.py
        django_uwsgi_config:
          app: wenet_survey
          settings: settings
        required_env_variables:
          - ${WENET_APP_ID}
          - ${WENET_APP_SECRET}
          - ${WENET_INSTANCE_URL}
          - ${OAUTH_CALLBACK_URL}
          - ${SURVEY_FORM_ID}
      - name: worker
        required_env_variables:
        custom_start_command: "exec celery -A wenet_survey worker -B -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"

    ci_environments:
      mr:
        stages:
          - name: build
            manual: true
          - name: test
      issue:
        stages:
          - name: build
            manual: true
          - name: test
          - name: push
          - name: deploy
            manual: true
          - name: stop
      staging:
        stages:
          - name: build
          - name: test
          - name: push
          - name: deploy
            manual: true
          - name: stop
      production:
        stages:
          - name: build
          - name: test
          - name: push
          - name: deploy
            manual: true
          - name: stop
    ci_additional_badges:
      - wenet-common

  roles:
    - uh.project_template