---

- name: Setup project.
  hosts: 127.0.0.1
  connection: local
  vars:
    project_type: python
    project_path: .
    project_features:
      - test
      - docker
    project_python_submodules: []

    docker_image_name: wenet/survey-app
    docker_python_services: 
      - name: survey
        main_module: manage.py
        django_uwsgi_config:
          app: wenet_survey
          settings: settings

    ci_environments:
      mr:
        stages:
          - name: build
            manual: true
          - name: test
      issue:
        stages:
          - name: build
            manual: true
          - name: test
      staging:
        stages:
          - name: build
            manual: true
          - name: test
      production:
        stages:
          - name: build
            manual: true
          - name: test
    ci_additional_badges:
      - wenet-common

  roles:
    - uh.project_template