# Generated by Django 3.2.6 on 2021-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedProfileUpdateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_datetime', models.DateTimeField()),
                ('wenet_id', models.CharField(max_length=1024)),
                ('raw_survey_answer', models.JSONField()),
            ],
            options={
                'verbose_name': 'Failed profile update task',
                'verbose_name_plural': 'Failed profile update tasks',
            },
        ),
        migrations.CreateModel(
            name='LastUserProfileUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('wenet_id', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Last user profile update',
                'verbose_name_plural': 'Last user profile updates',
            },
        ),
    ]
