---
- hosts: all
  name: Deploy storage.
  vars:
    postgres_docker_compose_folder: "{{ project_folder }}/wenet-survey-app-{{ service_environment }}-postgres"
    postgres_docker_networks: 
      - "{{ service_network }}"

    postgres_docker_volume: "wenet-survey-app-{{ service_environment }}-postgres"
    postgres_database_to_create: 
      - "{{ postgres_db_name_site }}"
      - "{{ postgres_db_name_celery }}"

    tear_down: false
    tear_down_remove_traefik: false
    tear_down_remove_volumes: false
    
  roles:
    - uh.deploy-postgres

- hosts: all
  name: Deploy services.
  vars:
    file_and_dir_group: deployers

    registry_url: registry.u-hopper.com
    registry_username: gitlab
    registry_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39323964306436303338633864376239393639353032383633616536383065396631373166313338
          3133646633343465316535626264393931643936363238320a323762363938653831623161636466
          61656234383636616431393065363232303439306430333139363366356166373766383038323366
          3234376631366531660a373265366464393839656565613661666332376235306631333533613161
          63663133343835386465656364613966306238666333346230323936666136366264363431313035
          3265343764363464356336336165393063303164343664643235



    docker_compose_folder: "{{ project_folder }}/wenet-survey-app-{{ service_environment }}"
    docker_file_template: templates/docker-compose-services.yml.j2
    docker_services:
      - site

    site_container_name: "wenet-survey-app-{{ service_environment }}"


    docker_networks: "{{ service_networks }}"

    site_postgres_user: postgres
    site_postgres_password: "{{ postgress_root_password }}"

    tear_down: false
    tear_down_remove_traefik: false
    tear_down_remove_volumes: false

  roles:
    - uh.deploy-docker-service
