roles:
  - src: ssh://git@lab.u-hopper.com:4422/devops/ansible/deploy-docker-service.git
    name: uh.deploy-docker-service
    version: 1.8.0
    scm: git

  - src: ssh://git@lab.u-hopper.com:4422/devops/ansible/deploy-postgres-ansible-role.git
    name: uh.deploy-postgres
    version: 0.1.0
    scm: git
